version: "3"

services:
  ner:
    container_name: ner
    build:
      context: .
      dockerfile: ./services/ner/Dockerfile
    volumes:
      - ./services/ner:/src
      - ~/data:/data
    ports:
      - 8000:8000
    environment:
      - CUDA_VISIBLE_DEVICES=5

  entity-linking:
    build:
      context: .
      dockerfile: ./services/entity_linking/Dockerfile
    volumes:
      - ./services/entity_linking:/src
      - ~/data:/data
    ports:
      - 8001:8001
    environment:
      - CUDA_VISIBLE_DEVICES=0

  topics:
    container_name: topics
    build:
      context: .
      dockerfile: ./services/topics/Dockerfile
    volumes:
      - ./services/topics:/src
      - ~/data:/data
    ports:
      - 8002:8002
    environment:
      - CUDA_VISIBLE_DEVICES=4

  sentiment:
    container_name: sentiment
    build:
      context: .
      dockerfile: ./services/sentiment/Dockerfile
    volumes:
      - ./services/sentiment:/src
    ports:
      - 8003:8003
    environment:
      - CUDA_VISIBLE_DEVICES=4

  call-to-action:
    build:
      context: .
      dockerfile: ./services/call_to_action/Dockerfile
    volumes:
      - ./services/call_to_action:/src
      - ~/data:/data
    ports:
      - 8004:8004
    environment:
      - CUDA_VISIBLE_DEVICES=4